from pathlib import Path

SECTIONS = [
    (
        "# Core Module Documentation\n\n"
        "## Purpose of `core/`\n\n"
        "The `core/` package contains the **solver-agnostic foundation** of the VSRP codebase.\n\n"
        "Its responsibilities are to:\n"
        "- define canonical problem and solution entities\n"
        "- build and describe the recovery network\n"
        "- recompute costs from canonical solutions\n"
        "- compute emissions and regulatory metrics\n"
        "- simulate realized performance under uncertainty\n"
        "- validate extracted solutions independently of the solver backend\n\n"
        "This package is the architectural center of the repository. Other layers\n"
        "such as `model/`, `experiments/`, and `reporting/` depend heavily on it,\n"
        "but `core/` itself does not depend on solver-specific APIs.\n\n"
        "---\n\n"
        "## Why `core/` matters\n\n"
        "The project is designed around two canonical shared objects:\n"
        "- `VSRPInstance`\n"
        "- `VSRPSolution`\n\n"
        "These objects allow the codebase to:\n"
        "- solve the same model with multiple backends\n"
        "- benchmark solvers consistently\n"
        "- recompute costs and emissions independently of the solver\n"
        "- validate results in a solver-agnostic way\n"
        "- feed tidy outputs into reporting and plots\n\n"
        "Without `core/`, the repository would collapse back into a set of\n"
        "solver-specific scripts instead of a reusable architecture.\n\n"
        "---\n\n"
        "## File overview\n\n"
        "| File | Main role |\n"
        "|---|---|\n"
        "| `entities.py` | Canonical dataclasses for instances, solutions, outcomes, solver stats, validation, emissions |\n"
        "| `network.py` | Builds the feasible route network, including skip edges and swap groups |\n"
        "| `costs.py` | Recomputes operational and service costs from canonical solutions |\n"
        "| `emissions.py` | Computes fuel, CO2, ETS, FuelEU, CII, and emissions summaries |\n"
        "| `simulation.py` | Simulates realized performance under uncertainty for CFA and stochastic experiments |\n"
        "| `validation.py` | Solver-agnostic route / strategy / timeline / structural consistency checks |\n\n"
        "---\n\n"
        "## 1. `core/entities.py`\n\n"
        "### Purpose\n\n"
        "`entities.py` defines the **canonical data model** of the repository.\n\n"
        "It contains all of the key dataclasses used to represent:\n"
        "- input data\n"
        "- network edges\n"
        "- solved route legs\n"
        "- strategy decisions\n"
        "- container outcomes\n"
        "- solver statistics\n"
        "- validation summaries\n"
        "- emissions summaries\n"
        "- experiment/benchmark records\n\n"
        "This file is foundational because it decouples the rest of the project\n"
        "from solver-specific data structures.\n\n"
        "### Most important classes\n\n"
        "#### `Container`\n"
        "Represents one cargo demand item, including:\n"
        "- origin and destination indices\n"
        "- promised arrival\n"
        "- delay penalty\n"
        "- misconnection penalty\n"
        "- optional transshipment port(s)\n"
        "- optional connecting-service deadline\n\n"
        "This is the key service-level demand object.\n\n"
        "#### `Edge`\n"
        "Represents one feasible network arc in the recovery model.\n\n"
        "It stores:\n"
        "- from/to port indices\n"
        "- sailing speed\n"
        "- travel time\n"
        "- fuel cost\n"
        "- whether the edge is part of a swap group\n"
        "- which planned ports are skipped by traversing the edge\n\n"
        "This is the key network object used by both Xpress and the open-source MIP builder.\n\n"
        "#### `VSRPInstance`\n"
        "Represents one full optimization instance.\n\n"
        "It packages together:\n"
        "- ports\n"
        "- distance matrix\n"
        "- generated containers\n"
        "- delay level\n"
        "- speed levels\n"
        "- port-call profile\n"
        "- penalties\n"
        "- swap settings\n"
        "- fuel / FuelEU settings\n\n"
        "This is the main problem object passed into all solver backends.\n\n"
        "#### `VSRPSolution`\n"
        "Represents one canonical solved solution.\n\n"
        "It may include:\n"
        "- selected route legs\n"
        "- skipped ports\n"
        "- swapped ports\n"
        "- strategy decisions\n"
        "- timeline\n"
        "- container outcomes\n"
        "- solver stats\n"
        "- validation result\n"
        "- emissions summary\n\n"
        "This is the main solved object consumed by experiments and reporting.\n\n"
        "### Design significance\n\n"
        "The canonical dataclasses are one of the strongest architectural choices\n"
        "in the project. They make it possible to:\n"
        "- compare different solvers fairly\n"
        "- recompute diagnostics outside the solver\n"
        "- treat experiments as consumers of normalized outputs instead of\n"
        "  solver-specific data\n\n"
        "---\n\n"
        "## 2. `core/network.py`\n\n"
        "### Purpose\n\n"
        "`network.py` builds the **feasible routing network** used by the optimization model.\n\n"
        "It is responsible for translating the high-level route structure into a set of\n"
        "feasible edges that can be selected by the MIP.\n\n"
        "### Main responsibilities\n\n"
        "#### Forward edges\n"
        "The module creates forward edges from port `i` to port `j` where:\n"
        "- `j > i`\n"
        "- no more than `max_skip` planned ports are skipped\n\n"
        "These edges implement normal progression through the route, including omissions.\n\n"
        "#### Swap groups\n"
        "If swapping is enabled, the module creates swap groups with three structural legs:\n"
        "- Leg A: predecessor of `i` to `j`\n"
        "- Leg B: `j` back to `i`\n"
        "- Leg C: `i` forward to successor of `j`\n\n"
        "Each swap group is identified by a shared `swap_group_id`.\n\n"
        "This network-level representation is what allows the optimization model to express\n"
        "non-adjacent port reordering.\n\n"
        "### Helper functions\n\n"
        "#### `build_network()`\n"
        "Constructs the full edge list.\n\n"
        "#### `build_network_from_instance()`\n"
        "Convenience wrapper that reads the relevant fields from `VSRPInstance`.\n\n"
        "#### `get_swap_groups()` / `get_swap_group_ids()`\n"
        "Utilities for grouping and indexing swap edges.\n\n"
        "#### `get_swap_group_port_pair()`\n"
        "Recovers the actual swapped port pair `(i, j)` from a swap group's reverse leg.\n\n"
        "#### `compute_planned_arrivals()` / `compute_planned_departures()`\n"
        "Build nominal timeline references used in solution reconstruction and validation.\n\n"
        "### Design significance\n\n"
        "This file isolates all optimization-independent route-network logic from the solver layer.\n"
        "That is why both the Xpress backend and the PuLP builder can use the same network structure.\n\n"
        "---\n\n"
        "## 3. `core/costs.py`\n\n"
        "### Purpose\n\n"
        "`costs.py` recomputes the objective decomposition from a canonical solution.\n\n"
        "This is important for:\n"
        "- validating solver output\n"
        "- detecting objective inconsistencies\n"
        "- producing report-ready cost breakdowns\n\n"
        "### Main outputs\n\n"
        "#### `CostBreakdown`\n"
        "A structured dataclass containing:\n"
        "- fuel cost\n"
        "- port-call cost\n"
        "- strategy penalty cost\n"
        "- port-specific penalty cost\n"
        "- FuelEU penalty cost\n"
        "- delay cost\n"
        "- misconnection cost\n"
        "- operational cost\n"
        "- service cost\n"
        "- weighted objective\n\n"
        "#### `compute_cost_breakdown()`\n"
        "The main entry point for post-solve cost recomputation.\n\n"
        "### Important modeling detail\n\n"
        "The swap penalty is charged **once per active swap group**, not once per swapped port.\n\n"
        "This matters because:\n"
        "- the canonical solution reports `PORT_SWAP` tags per swapped port\n"
        "- but the optimization model treats one swap action as one group-level decision\n\n"
        "This alignment is essential for obtaining near-zero objective recomputation gaps.\n\n"
        "---\n\n"
        "## 4. `core/emissions.py`\n\n"
        "### Purpose\n\n"
        "`emissions.py` computes environmental and regulatory metrics from route legs or full solutions.\n\n"
        "This file is one of the most important extensions relative to the original notebook.\n\n"
        "### Main capabilities\n\n"
        "#### Fuel and CO2\n"
        "Uses a cubic-speed fuel model to estimate:\n"
        "- fuel consumption per leg\n"
        "- total fuel burn\n"
        "- CO2 emissions using a VLSFO emission factor\n\n"
        "#### EU ETS\n"
        "Computes ETS exposure using:\n"
        "- CO2 emissions\n"
        "- carbon price\n"
        "- EU ETS phase-in schedule\n\n"
        "#### FuelEU Maritime\n"
        "Computes a FuelEU non-compliance penalty using an energy-based formulation.\n\n"
        "#### CII\n"
        "Computes:\n"
        "- attained CII\n"
        "- required CII\n"
        "- A–E rating\n\n"
        "#### EEXI scaffolding\n"
        "Provides vessel-level EEXI compliance support.\n\n"
        "### Main functions\n\n"
        "#### `compute_leg_emission_record()`\n"
        "Computes emissions and regulatory exposure for one route leg.\n\n"
        "#### `compute_solution_leg_emissions()`\n"
        "Computes leg-level emissions records for an extracted solution.\n\n"
        "#### `compute_solution_emissions_summary()`\n"
        "Main entry point for solution-level emissions summaries.\n\n"
        "### Important assumptions\n\n"
        "- single-fuel VLSFO assumption\n"
        "- constant GHG intensity across all legs\n"
        "- FuelEU modeled as a voyage-level proxy rather than annual compliance\n\n"
        "These assumptions are reasonable for the current case-study scope but should be stated clearly.\n\n"
        "---\n\n"
        "## 5. `core/simulation.py`\n\n"
        "### Purpose\n\n"
        "`simulation.py` provides the uncertainty and realized-performance layer used by CFA and stochastic experiments.\n\n"
        "This file is what turns a deterministic optimization model into a repeated-decision system under uncertainty.\n\n"
        "### Main concepts\n\n"
        "#### `UncertaintyScenario`\n"
        "Represents one realized episode, including:\n"
        "- realized initial delay\n"
        "- port handling multipliers\n"
        "- weather speed factors\n"
        "- realized carbon price\n"
        "- realized fuel price\n\n"
        "#### `UncertaintyConfig`\n"
        "Stores the distribution settings used to sample uncertainty.\n\n"
        "#### `sample_uncertainty_scenario()`\n"
        "Draws one realized scenario for simulation.\n\n"
        "#### `compute_actual_route_arrivals()`\n"
        "Reconstructs actual arrival times for a fixed route under a realized scenario.\n\n"
        "#### `simulate_realized_performance()`\n"
        "Evaluates a solved route under realized uncertainty and returns:\n"
        "- missed containers\n"
        "- service cost\n"
        "- realized fuel cost\n"
        "- realized ETS cost\n\n"
        "### Design significance\n\n"
        "This file is crucial for the CFA framework because the optimization problem is solved on an estimated state,\n"
        "but evaluated on a realized state.\n\n"
        "That separation between **planning** and **realization** is central to the policy-learning setup.\n\n"
        "---\n\n"
        "## 6. `core/validation.py`\n\n"
        "### Purpose\n\n"
        "`validation.py` provides solver-agnostic consistency checks for extracted solutions.\n\n"
        "This is important because solver feasibility alone is not enough once solutions are:\n"
        "- reconstructed into route legs\n"
        "- tagged with strategies\n"
        "- converted into timelines\n"
        "- compared across multiple backends\n\n"
        "### Validation layers\n\n"
        "#### Route validation\n"
        "Checks:\n"
        "- non-empty route\n"
        "- valid port indices\n"
        "- starts at origin\n"
        "- ends at sink\n"
        "- adjacency continuity\n"
        "- no repeated interior visits\n\n"
        "#### Timeline validation\n"
        "Checks:\n"
        "- valid timeline entries\n"
        "- departure not before arrival\n"
        "- monotonic chronology\n"
        "- consistent stored delay values\n\n"
        "#### Strategy validation\n"
        "Checks:\n"
        "- skipped ports vs omission tags\n"
        "- swapped ports vs swap tags\n"
        "- basic swap-group route integrity\n\n"
        "#### Container validation\n"
        "Checks:\n"
        "- outcome records exist for all containers\n"
        "- origin/destination consistency\n"
        "- transshipment consistency\n\n"
        "#### Structural constraint residuals\n"
        "Reconstructs approximate numerical residuals for:\n"
        "- flow balance\n"
        "- port-call consistency\n"
        "- omission consistency\n\n"
        "### Important design note\n\n"
        "Delay-classification consistency is **not** treated as a hard numerical violation.\n"
        "This is intentional because:\n"
        "- the MIP delay variable uses a conservative approximation\n"
        "- the reporting timeline is more explicit\n"
        "- the two can differ without implying model infeasibility\n\n"
        "This is a subtle but important modeling choice.\n\n"
        "---\n\n"
        "## Summary of `core/`\n\n"
        "The `core/` package is the shared foundation of the repository.\n\n"
        "It is responsible for:\n"
        "- defining the language of the optimization problem\n"
        "- representing route/network structure\n"
        "- turning solver outputs into meaningful business and regulatory metrics\n"
        "- validating extracted solutions independently of the solver\n"
        "- enabling simulation and CFA under uncertainty\n\n"
        "If `model/` is the optimization engine, then `core/` is the shared domain model and analytics layer.\n\n"
        "---\n\n"
        "## Suggested next documentation layers\n\n"
        "After `core/`, the next most useful documents are:\n"
        "- `03_data.md` — how instances and containers are generated\n"
        "- `04_model.md` — how Xpress, HiGHS, CBC, and the MIP builder work\n"
    )
]

content = "".join(SECTIONS)

output_dir = Path("docs")
output_dir.mkdir(parents=True, exist_ok=True)

output_path = output_dir / "02_core.md"
output_path.write_text(content, encoding="utf-8")

print(f"Written: {output_path.resolve()}")
print("Preview in VS Code Markdown Preview or any Markdown viewer.")