from pathlib import Path

SECTIONS = [
    (
        "# Data Module Documentation\n\n"
        "## Purpose of `data/`\n\n"
        "The `data/` package is responsible for constructing the **input side** of the VSRP.\n\n"
        "It defines:\n"
        "- the fixed case-study route and distance matrix\n"
        "- default speed, port-call, and penalty settings\n"
        "- random container generation logic\n"
        "- helper factories for reproducible instances\n\n"
        "In architectural terms, `data/` answers the question:\n\n"
        "> **what optimization problem instance are we solving?**\n\n"
        "It is the layer that produces canonical `VSRPInstance` objects for the solver backends.\n\n"
        "---\n\n"
        "## Files in `data/`\n\n"
        "| File | Main role |\n"
        "|---|---|\n"
        "| `base_instance.py` | Defines the fixed case-study route, default parameters, and instance factory |\n"
        "| `instance_generator.py` | Generates random container sets and calibrates promised arrivals / penalties |\n\n"
        "---\n\n"
        "## Architectural role of `data/`\n\n"
        "The repository is built around canonical `VSRPInstance` objects.\n"
        "Those objects are not assembled manually inside the solver code.\n"
        "Instead, they are created by the data layer.\n\n"
        "This separation is important because it allows:\n"
        "- reproducible experiments under different seeds\n"
        "- sensitivity analysis on fixed demand sets\n"
        "- easy reuse of the same instance across multiple solver backends\n"
        "- clear separation between **problem generation** and **problem solving**\n\n"
        "---\n\n"
        "## 1. `data/base_instance.py`\n\n"
        "### Purpose\n\n"
        "`base_instance.py` defines the **fixed case-study route** and the default operational settings\n"
        "used across the repository.\n\n"
        "It is the closest thing in the codebase to a static scenario template.\n\n"
        "### Main contents\n\n"
        "#### `BASE_PORTS`\n"
        "The nominal planned route, represented as an ordered list of ports.\n\n"
        "This order matters because:\n"
        "- the network generator builds forward edges relative to this sequence\n"
        "- swap feasibility is defined relative to this sequence\n"
        "- planned arrivals and departures assume this sequence\n\n"
        "#### `BASE_DISTANCE_MATRIX_NM`\n"
        "Pairwise distance matrix aligned with `BASE_PORTS`.\n\n"
        "This matrix is used by:\n"
        "- network generation\n"
        "- travel-time calculation\n"
        "- fuel and emissions calculation\n"
        "- planned schedule reconstruction\n\n"
        "#### `DEFAULT_SPEED_LEVELS_KNOTS`\n"
        "The discrete sailing speed options used by the optimization model.\n\n"
        "#### `DEFAULT_PORT_CALL_PROFILE`\n"
        "The default port-call duration and handling-cost options.\n\n"
        "In the current project, these are:\n"
        "- STANDARD\n"
        "- EXPEDITED\n\n"
        "#### `DEFAULT_PENALTIES`\n"
        "Default tactical penalty settings for:\n"
        "- speed-up\n"
        "- expedited port\n"
        "- omission\n"
        "- swap\n\n"
        "### Main function\n\n"
        "#### `build_base_instance()`\n"
        "This is the main factory function in the file.\n\n"
        "It builds a canonical `VSRPInstance` from:\n"
        "- generated containers\n"
        "- the fixed route template\n"
        "- default or overridden operational settings\n\n"
        "### Why this file matters\n\n"
        "This file ensures that all experiments share a consistent baseline network.\n"
        "Without it, every script would need to manually rebuild route, speed, penalty,\n"
        "and regulation settings, which would make reproducibility much weaker.\n\n"
        "---\n\n"
        "## 2. `data/instance_generator.py`\n\n"
        "### Purpose\n\n"
        "`instance_generator.py` creates random container demand sets that are still\n"
        "internally consistent with the route and timing assumptions of the model.\n\n"
        "This file is critical because the project’s behavior depends heavily on how:\n"
        "- promised arrivals are calibrated\n"
        "- penalties are assigned\n"
        "- transshipment containers are created\n\n"
        "### Main design goal\n\n"
        "The generator is not just producing random origin-destination pairs.\n"
        "It is also producing **service promises** that are meant to be meaningful\n"
        "under the model’s nominal timing assumptions.\n\n"
        "That is why promised-arrival calibration is one of the most important design choices here.\n\n"
        "---\n\n"
        "## Promised-arrival calibration\n\n"
        "### Why it matters\n\n"
        "If promised arrivals are calibrated against a zero-delay baseline, then any non-zero\n"
        "initial disruption immediately makes all containers structurally late.\n\n"
        "That destroys the usefulness of:\n"
        "- delay sensitivity experiments\n"
        "- CFA learning signal\n"
        "- realistic service-cost trade-offs\n\n"
        "### Current approach\n\n"
        "The generator computes nominal arrivals using:\n"
        "- nominal speed\n"
        "- nominal port-call duration\n"
        "- **expected initial delay**\n\n"
        "Then it adds promised slack on top.\n\n"
        "This means container promises are calibrated to realistic disrupted operations,\n"
        "not to an unrealistic zero-delay world.\n\n"
        "This is a major improvement over a naive promise generator.\n\n"
        "---\n\n"
        "## Main components of `instance_generator.py`\n\n"
        "### `cumulative_nominal_arrivals()`\n"
        "Computes nominal cumulative arrival times along the route.\n\n"
        "This helper underpins promise calibration and transshipment deadline generation.\n\n"
        "### `generate_containers()`\n"
        "The main random demand generator.\n\n"
        "It samples:\n"
        "- origin and destination\n"
        "- quantity\n"
        "- priority\n"
        "- optional transshipment structure\n"
        "- promised arrival\n"
        "- penalties\n\n"
        "### `generate_small_test_set()`\n"
        "Convenience wrapper for quick debugging / smoke testing.\n\n"
        "### `generate_transshipment_test_set()`\n"
        "Convenience wrapper for generating mixed direct/transshipment demand sets.\n\n"
        "---\n\n"
        "## Container penalties\n\n"
        "The generator supports two broad modes:\n\n"
        "### Notebook-compatible mode\n"
        "Delay penalty is based on the original notebook-style scaling,\n"
        "and misconnection uses a fixed penalty.\n\n"
        "This mode helps preserve comparability with the original baseline implementation.\n\n"
        "### Stress-test mode\n"
        "Delay and misconnection penalties are drawn from wider random ranges.\n\n"
        "This mode is more useful for experimentation and robustness testing.\n\n"
        "---\n\n"
        "## Transshipment generation\n\n"
        "If transshipment generation is enabled:\n"
        "- a transshipment port is selected between origin and destination\n"
        "- a connecting-service deadline is constructed from the nominal schedule\n"
        "- the resulting container becomes subject to misconnection logic in the model\n\n"
        "This provides a compact way to represent transshipment without explicitly modeling\n"
        "a second vessel or downstream service network.\n\n"
        "---\n\n"
        "## Why the data layer is important\n\n"
        "The `data/` package determines the experimental behavior of the whole project.\n"
        "Even if the optimization model is correct, poor data generation can make results:\n"
        "- trivial\n"
        "- insensitive\n"
        "- unrealistic\n"
        "- impossible to interpret\n\n"
        "Your repository avoids that by carefully calibrating promises, delays,\n"
        "penalties, and optional transshipment structure.\n\n"
        "---\n\n"
        "## Relationship to the rest of the codebase\n\n"
        "### `data/` -> `model/`\n"
        "The data layer creates the canonical `VSRPInstance` consumed by the solvers.\n\n"
        "### `data/` -> `experiments/`\n"
        "Experiments repeatedly call the generator with different seeds or settings to\n"
        "produce controlled input variation.\n\n"
        "### `data/` -> `core/`\n"
        "The data layer uses canonical dataclasses from `core/entities.py`.\n\n"
        "---\n\n"
        "## Summary of `data/`\n\n"
        "The `data/` package is the instance-construction layer of the repository.\n\n"
        "It provides:\n"
        "- the fixed route template\n"
        "- default speed and penalty settings\n"
        "- reproducible random container generation\n"
        "- calibrated service promises\n"
        "- optional transshipment demand\n\n"
        "This makes it possible to run reproducible and interpretable experiments\n"
        "without embedding instance-generation logic inside the solver or experiment code.\n\n"
        "---\n\n"
        "## Suggested next documentation layer\n\n"
        "After `data/`, the next most useful document is:\n"
        "- `04_model.md` — the optimization backends and MIP builder\n"
    )
]

content = "".join(SECTIONS)

output_dir = Path("docs")
output_dir.mkdir(parents=True, exist_ok=True)

output_path = output_dir / "03_data.md"
output_path.write_text(content, encoding="utf-8")

print(f"Written: {output_path.resolve()}")
print("Preview in VS Code Markdown Preview or any Markdown viewer.")