from pathlib import Path

SECTIONS = [
    (
        "# Reporting Module Documentation\n\n"
        "## Purpose of `reporting/`\n\n"
        "The `reporting/` package converts experiment outputs into persistent artifacts:\n"
        "- tables\n"
        "- figures\n"
        "- compact console summaries\n\n"
        "If `experiments/` produces the analytical results, then `reporting/` is the layer\n"
        "that turns those results into something reusable for:\n"
        "- the case-study report\n"
        "- benchmark comparison\n"
        "- exploratory analysis\n"
        "- result archiving\n\n"
        "---\n\n"
        "## Files in `reporting/`\n\n"
        "| File | Main role |\n"
        "|---|---|\n"
        "| `export.py` | Shared utilities for saving DataFrames and figures |\n"
        "| `benchmark_reporting.py` | Benchmark table saving and console summaries |\n"
        "| `benchmark_plots.py` | Benchmark visualization |\n"
        "| `sensitivity_plots.py` | Alpha and delay sensitivity plots |\n"
        "| `emissions_plots.py` | Emissions, ETS, FuelEU, and CII plots |\n"
        "| `cfa_plots.py` | CFA policy comparison and risk plots |\n"
        "| `penalty_sensitivity_plots.py` | Penalty sensitivity overview plots |\n"
        "| `stochastic_ets_plots.py` | Stochastic ETS exposure plots |\n\n"
        "---\n\n"
        "## Architectural role of `reporting/`\n\n"
        "The reporting layer is deliberately separated from:\n"
        "- optimization logic\n"
        "- instance generation\n"
        "- simulation logic\n\n"
        "This separation matters because it allows the repository to:\n"
        "- regenerate figures without modifying optimization code\n"
        "- keep plotting concerns out of the solver layer\n"
        "- make experiment outputs portable and easy to reuse\n\n"
        "The typical workflow is:\n\n"
        "1. `experiments/*` returns a DataFrame or structured result\n"
        "2. `reporting/*` saves it or visualizes it\n"
        "3. files are written under `results/`\n\n"
        "---\n\n"
        "## 1. `reporting/export.py`\n\n"
        "### Purpose\n\n"
        "`export.py` contains the shared low-level output utilities used by the other reporting modules.\n\n"
        "It is the foundation of the reporting layer.\n\n"
        "### Main functions\n\n"
        "#### `ensure_directory()`\n"
        "Creates output directories if they do not already exist.\n\n"
        "This avoids repeating directory-creation logic throughout plotting and export code.\n\n"
        "#### `save_dataframe()`\n"
        "Saves a pandas DataFrame to:\n"
        "- CSV\n"
        "- Excel\n\n"
        "This is used by benchmark, sensitivity, CFA, penalty, and stochastic ETS scripts.\n\n"
        "#### `save_figure()`\n"
        "Saves matplotlib figures to:\n"
        "- PNG\n"
        "- PDF\n\n"
        "This centralization is valuable because it:\n"
        "- enforces consistent output behavior\n"
        "- removes duplicated save logic across plotting modules\n"
        "- makes the reporting layer easier to maintain\n\n"
        "---\n\n"
        "## 2. `reporting/benchmark_reporting.py`\n\n"
        "### Purpose\n\n"
        "This file handles benchmark-oriented table export and compact console summaries.\n\n"
        "### Main functions\n\n"
        "#### `save_benchmark_outputs()`\n"
        "Saves:\n"
        "- raw benchmark rows\n"
        "- solver-level benchmark summary table\n\n"
        "#### `print_benchmark_summary()`\n"
        "Prints a compact benchmark summary to the console.\n\n"
        "### Why this file matters\n\n"
        "It provides a lightweight textual reporting path in addition to saved tables and plots.\n\n"
        "---\n\n"
        "## 3. `reporting/benchmark_plots.py`\n\n"
        "### Purpose\n\n"
        "This module visualizes solver benchmark summaries.\n\n"
        "### Main function\n\n"
        "#### `plot_benchmark_summary()`\n"
        "Creates a multi-panel figure showing metrics such as:\n"
        "- average objective\n"
        "- average runtime\n"
        "- average MIP gap\n\n"
        "### Why this file matters\n\n"
        "Benchmark tables are useful, but visual comparison makes performance differences much easier to communicate.\n\n"
        "---\n\n"
        "## 4. `reporting/sensitivity_plots.py`\n\n"
        "### Purpose\n\n"
        "This module visualizes deterministic sensitivity experiments.\n\n"
        "### Main functions\n\n"
        "#### `plot_alpha_sweep()`\n"
        "Plots the effect of the service-weight parameter `alpha` on:\n"
        "- objective\n"
        "- cost decomposition\n"
        "- service outcomes\n"
        "- emissions\n\n"
        "#### `plot_delay_sweep()`\n"
        "Plots the effect of initial disruption delay on:\n"
        "- objective\n"
        "- cost decomposition\n"
        "- service outcomes\n"
        "- emissions / ETS cost\n\n"
        "#### `plot_alpha_pareto()`\n"
        "Creates a Pareto-style operational-cost vs service-cost trade-off plot.\n\n"
        "### Why this file matters\n\n"
        "It helps translate raw sensitivity tables into interpretable economic trade-off figures.\n\n"
        "---\n\n"
        "## 5. `reporting/emissions_plots.py`\n\n"
        "### Purpose\n\n"
        "This module focuses specifically on environmental and regulatory visualizations.\n\n"
        "### Main functions\n\n"
        "#### `plot_green_recovery_tradeoff()`\n"
        "Shows how cost, service, and emissions move across alpha values.\n\n"
        "#### `plot_emissions_vs_delay_penalty()`\n"
        "Shows the relationship between CO2 burden and delay-service penalties across disruption scenarios.\n\n"
        "#### `plot_strategy_mix_under_ets()`\n"
        "Shows route strategy composition together with emissions / ETS exposure under varying ETS carbon prices.\n\n"
        "Important interpretation:\n"
        "this is currently best understood as an **ETS exposure** visualization,\n"
        "not a fully endogenous carbon-price-in-objective policy-response plot.\n\n"
        "#### `plot_ets_phase_in_impact()`\n"
        "Illustrates how ETS burden changes across regulatory phase-in years.\n\n"
        "#### `plot_cii_profile()`\n"
        "Plots attained versus required CII across disruption scenarios, colored by rating.\n\n"
        "### Why this file matters\n\n"
        "This file is the main vehicle for communicating the environmental contribution of the project.\n\n"
        "---\n\n"
        "## 6. `reporting/cfa_plots.py`\n\n"
        "### Purpose\n\n"
        "This module visualizes CFA policy learning and evaluation results.\n\n"
        "### Main functions\n\n"
        "#### `plot_theta_evolution()`\n"
        "Shows how the learned tightening vector evolves over training episodes.\n\n"
        "#### `plot_cfa_policy_comparison()`\n"
        "Compares policies across realized metrics such as:\n"
        "- cumulative misses\n"
        "- realized service cost\n"
        "- realized ETS cost\n\n"
        "#### `plot_cfa_summary_bars()`\n"
        "Provides average realized-policy comparison in bar-chart form.\n\n"
        "#### `plot_cfa_tail_risk()`\n"
        "Shows the distribution of realized service cost with p90/p95 emphasis.\n\n"
        "#### `plot_ets_compliance_rate()`\n"
        "Visualizes regulatory compliance-style metrics and realized ETS exposure.\n\n"
        "### Important design note\n\n"
        "CFA plots are intentionally based on **realized metrics**, not raw optimization objectives,\n"
        "because different policies solve differently tightened optimization instances.\n\n"
        "### Why this file matters\n\n"
        "It is what makes the CFA results interpretable and report-ready.\n\n"
        "---\n\n"
        "## 7. `reporting/penalty_sensitivity_plots.py`\n\n"
        "### Purpose\n\n"
        "This module visualizes tactical penalty-sensitivity experiments.\n\n"
        "### Main function\n\n"
        "#### `plot_penalty_sweep_overview()`\n"
        "Creates a compact multi-panel overview showing:\n"
        "- average objective\n"
        "- average service/strategy counts\n"
        "- average emissions\n"
        "- fraction of seeds with route or strategy change\n\n"
        "### Why this file matters\n\n"
        "Penalty experiments often need both:\n"
        "- cost interpretation\n"
        "- structural-change interpretation\n\n"
        "This module supports both in one figure.\n\n"
        "---\n\n"
        "## 8. `reporting/stochastic_ets_plots.py`\n\n"
        "### Purpose\n\n"
        "This module visualizes stochastic ETS exposure distributions.\n\n"
        "### Main function\n\n"
        "Typical plots here show:\n"
        "- realized carbon price vs ETS cost\n"
        "- ETS cost distribution / histogram\n\n"
        "### Why this file matters\n\n"
        "Tables of stochastic ETS scenarios are useful, but distributional plots make\n"
        "tail exposure much easier to understand.\n\n"
        "---\n\n"
        "## Common reporting pattern\n\n"
        "Most reporting modules follow the same simple pattern:\n\n"
        "1. receive a DataFrame or structured result object\n"
        "2. perform light filtering / aggregation\n"
        "3. create a matplotlib figure or export table\n"
        "4. save output into `results/`\n\n"
        "This is intentionally lightweight. The reporting layer is not meant to contain\n"
        "business logic that belongs in `core/` or `experiments/`.\n\n"
        "---\n\n"
        "## Relationship to the rest of the codebase\n\n"
        "### `reporting/` depends on `experiments/`\n"
        "because experiments produce the tabular outputs that are visualized or exported.\n\n"
        "### `reporting/` depends on `export.py`\n"
        "for consistent save behavior across all table and figure outputs.\n\n"
        "### `scripts/` depends on `reporting/`\n"
        "because smoke scripts call reporting functions after experiments finish.\n\n"
        "---\n\n"
        "## Strengths of the `reporting/` layer\n\n"
        "- clean separation from solver logic\n"
        "- reusable table and figure outputs\n"
        "- centralized save helpers\n"
        "- consistent output directory structure\n"
        "- supports both exploratory and report-oriented workflows\n\n"
        "---\n\n"
        "## Current limitations of the `reporting/` layer\n\n"
        "- most plots assume experiment outputs have already been cleaned and are consistent\n"
        "- figure styles are informative but still relatively lightweight compared with publication-grade customization\n"
        "- some modules depend on fields only available from the full Xpress canonical solution path\n\n"
        "---\n\n"
        "## Summary of `reporting/`\n\n"
        "The `reporting/` package is the presentation and export layer of the repository.\n\n"
        "It turns experiment outputs into:\n"
        "- saved tables\n"
        "- benchmark figures\n"
        "- sensitivity figures\n"
        "- emissions and regulatory figures\n"
        "- CFA policy figures\n"
        "- penalty and stochastic ETS plots\n\n"
        "This layer is essential for reproducibility because it ensures that all major results\n"
        "can be regenerated directly from code.\n\n"
        "---\n\n"
        "## Suggested next documentation layer\n\n"
        "After `reporting/`, the next most useful document is:\n"
        "- `07_scripts.md` — the executable entry points and smoke-test workflow\n"
    )
]

content = "".join(SECTIONS)

output_dir = Path("docs")
output_dir.mkdir(parents=True, exist_ok=True)

output_path = output_dir / "06_reporting.md"
output_path.write_text(content, encoding="utf-8")

print(f"Written: {output_path.resolve()}")
print("Preview in VS Code Markdown Preview or any Markdown viewer.")