from pathlib import Path

SECTIONS = [
    (
        "# Scripts Module Documentation\n\n"
        "## Purpose of `scripts/`\n\n"
        "The `scripts/` package contains the **user-facing executable entry points** of the repository.\n\n"
        "These files are not core logic modules. Instead, they are thin orchestration layers that:\n"
        "- build instances\n"
        "- choose solver backends\n"
        "- call experiment functions\n"
        "- print summaries to the console\n"
        "- save tables and figures into `results/`\n\n"
        "In practical terms, this is the part of the repository that a user runs directly.\n\n"
        "---\n\n"
        "## Why scripts matter\n\n"
        "Although the real logic lives in `core/`, `model/`, `experiments/`, and `reporting/`,\n"
        "the scripts are important because they provide:\n"
        "- reproducible end-to-end workflows\n"
        "- smoke tests for debugging and validation\n"
        "- convenient experiment runners\n"
        "- examples of how the architecture is meant to be used\n\n"
        "They also show the intended usage pattern of the codebase.\n\n"
        "---\n\n"
        "## Files in `scripts/`\n\n"
        "| File | Main role |\n"
        "|---|---|\n"
        "| `smoke_test.py` | End-to-end single-instance Xpress sanity check |\n"
        "| `transshipment_smoke.py` | Focused smoke test for transshipment logic across solvers |\n"
        "| `benchmark_smoke.py` | Small multi-solver benchmark run |\n"
        "| `sensitivity_smoke.py` | Alpha / delay / ETS sensitivity run |\n"
        "| `cfa_smoke.py` | CFA training and evaluation smoke test |\n"
        "| `penalty_sensitivity_smoke.py` | Multi-seed swap penalty experiment |\n"
        "| `penalty_speedup_multiseed_smoke.py` | Multi-seed speed-up penalty experiment |\n"
        "| `penalty_plot_smoke.py` | Plot-only runner for penalty sensitivity outputs |\n"
        "| `stochastic_ets_smoke.py` | Stochastic ETS exposure experiment |\n"
        "| `debug_alpha_case.py` | Detailed debugging view for one alpha scenario |\n\n"
        "---\n\n"
        "## General script pattern\n\n"
        "Most scripts follow the same structure:\n\n"
        "1. create or load a container set\n"
        "2. build one or more canonical instances\n"
        "3. choose a solver and solve options\n"
        "4. run one experiment or one direct solve\n"
        "5. print a readable summary\n"
        "6. save tables and/or figures\n\n"
        "This makes the script layer easy to understand and easy to extend.\n\n"
        "---\n\n"
        "## 1. `scripts/smoke_test.py`\n\n"
        "### Purpose\n\n"
        "This is the most important basic sanity-check script in the repository.\n\n"
        "It runs one small Xpress solve and prints:\n"
        "- generated containers\n"
        "- instance settings\n"
        "- route\n"
        "- strategy decisions\n"
        "- skipped and swapped ports\n"
        "- container outcomes\n"
        "- validation summary\n"
        "- emissions summary\n"
        "- cost breakdown\n\n"
        "### Why this script matters\n\n"
        "It is the fastest way to confirm that the full native workflow still works after code changes.\n\n"
        "If this script passes, then many core pieces are working together correctly:\n"
        "- instance generation\n"
        "- solver build/solve\n"
        "- route extraction\n"
        "- validation\n"
        "- emissions\n"
        "- cost recomputation\n\n"
        "---\n\n"
        "## 2. `scripts/transshipment_smoke.py`\n\n"
        "### Purpose\n\n"
        "This script stress-tests the transshipment and misconnection logic.\n\n"
        "It generates a mixed direct/transshipment container set and solves the same instance with:\n"
        "- Xpress\n"
        "- HiGHS\n"
        "- CBC\n\n"
        "### Why this script matters\n\n"
        "It specifically targets one of the major model extensions: transshipment misconnection.\n\n"
        "It also serves as a cross-solver objective-consistency check.\n\n"
        "### Important detail\n\n"
        "Only Xpress currently returns full route/timeline/container-output detail.\n"
        "HiGHS and CBC appear as partial-solution backends in this script.\n\n"
        "---\n\n"
        "## 3. `scripts/benchmark_smoke.py`\n\n"
        "### Purpose\n\n"
        "This script runs a small benchmark over multiple solvers on a few random instances.\n\n"
        "It prints:\n"
        "- solver availability\n"
        "- selected raw benchmark columns\n"
        "- benchmark summary table\n"
        "- stability metrics\n\n"
        "It also saves:\n"
        "- raw benchmark results\n"
        "- summary benchmark table\n"
        "- benchmark summary figure\n\n"
        "### Why this script matters\n\n"
        "It is the simplest executable proof that the benchmarking layer works end-to-end.\n\n"
        "---\n\n"
        "## 4. `scripts/sensitivity_smoke.py`\n\n"
        "### Purpose\n\n"
        "This script runs the main deterministic sensitivity experiments:\n"
        "- alpha sweep\n"
        "- delay sweep\n"
        "- ETS exposure sweep\n\n"
        "It saves both tables and plots.\n\n"
        "### Outputs typically include\n"
        "- objective trajectories\n"
        "- cost decomposition trends\n"
        "- service KPIs\n"
        "- emissions and ETS metrics\n"
        "- green recovery plots\n"
        "- CII profile plots\n\n"
        "### Why this script matters\n\n"
        "It is the quickest end-to-end test of the deterministic analytical layer of the repository.\n\n"
        "---\n\n"
        "## 5. `scripts/cfa_smoke.py`\n\n"
        "### Purpose\n\n"
        "This script runs the full CFA workflow on a small problem:\n"
        "- initialize baseline theta\n"
        "- train additive policy\n"
        "- train decay policy\n"
        "- train SPSA policy\n"
        "- test all policies on repeated stochastic episodes\n"
        "- compute tail-risk summaries\n"
        "- generate CFA plots\n\n"
        "### Why this script matters\n\n"
        "This is the main executable test of the stochastic learning extension of the project.\n\n"
        "It confirms that optimization, simulation, and policy updating are connected correctly.\n\n"
        "### Important interpretation\n\n"
        "The script emphasizes realized metrics rather than raw optimization objective values,\n"
        "because different CFA policies solve differently tightened optimization instances.\n\n"
        "---\n\n"
        "## 6. `scripts/penalty_sensitivity_smoke.py`\n\n"
        "### Purpose\n\n"
        "This script runs a multi-seed penalty sweep focused on swap penalty sensitivity.\n\n"
        "It prints:\n"
        "- seed\n"
        "- penalty value\n"
        "- objective\n"
        "- service/strategy counts\n"
        "- route and strategy signatures\n\n"
        "It also builds a summary of route/strategy change frequency by seed.\n\n"
        "### Why this script matters\n\n"
        "It is useful for identifying whether tactical recovery behavior is:\n"
        "- flat over a penalty range\n"
        "- threshold-sensitive\n"
        "- instance-dependent\n\n"
        "---\n\n"
        "## 7. `scripts/penalty_speedup_multiseed_smoke.py`\n\n"
        "### Purpose\n\n"
        "This script runs a multi-seed penalty sweep focused on speed-up penalty sensitivity.\n\n"
        "It helps determine whether the speed-up tactic is active, inactive, or threshold-sensitive\n"
        "under the current generated instances.\n\n"
        "### Why this script matters\n\n"
        "It complements the swap penalty script and helps assess whether the model is using\n"
        "speed-based recovery aggressively enough to show meaningful environmental trade-offs.\n\n"
        "---\n\n"
        "## 8. `scripts/penalty_plot_smoke.py`\n\n"
        "### Purpose\n\n"
        "This is a plot-only helper script.\n\n"
        "It reads already-saved CSV outputs from penalty experiments and generates:\n"
        "- swap penalty overview plots\n"
        "- speed-up penalty overview plots\n\n"
        "### Why this script matters\n\n"
        "It separates experiment execution from plotting, which can be useful when:\n"
        "- rerunning plots only\n"
        "- modifying figure aesthetics\n"
        "- testing plot modules without rerunning optimization\n\n"
        "---\n\n"
        "## 9. `scripts/stochastic_ets_smoke.py`\n\n"
        "### Purpose\n\n"
        "This script runs the stochastic ETS exposure experiment.\n\n"
        "It:\n"
        "- solves one deterministic instance\n"
        "- samples many carbon-price scenarios\n"
        "- recomputes ETS exposure for the fixed route\n"
        "- prints scenario rows and distribution summaries\n"
        "- saves the resulting table\n\n"
        "### Why this script matters\n\n"
        "It is the simplest executable demonstration of the repository’s stochastic regulatory-risk analysis.\n\n"
        "---\n\n"
        "## 10. `scripts/debug_alpha_case.py`\n\n"
        "### Purpose\n\n"
        "This is a diagnostic script for one selected alpha scenario.\n\n"
        "It prints detailed information about:\n"
        "- containers\n"
        "- solved route\n"
        "- skipped and swapped ports\n"
        "- timeline\n"
        "- validation\n"
        "- cost breakdown\n"
        "- emissions\n\n"
        "### Why this script matters\n\n"
        "When a sensitivity result looks surprising, this script provides a detailed view into one case.\n"
        "It is especially useful for debugging route reconstruction or timeline behavior.\n\n"
        "---\n\n"
        "## Relationship to the rest of the codebase\n\n"
        "### `scripts/` depends on `experiments/`\n"
        "for higher-level orchestration functions such as benchmarking, sensitivity, CFA,\n"
        "penalty sweeps, and stochastic ETS.\n\n"
        "### `scripts/` depends on `model/`\n"
        "for direct solver selection in smoke and debugging workflows.\n\n"
        "### `scripts/` depends on `reporting/`\n"
        "for saving tables and figures.\n\n"
        "### `scripts/` may depend directly on `data/`\n"
        "for direct instance construction in lower-level smoke or diagnostic scripts.\n\n"
        "---\n\n"
        "## Why scripts are kept thin\n\n"
        "A major design choice in the repository is to keep scripts as thin as possible.\n\n"
        "That means:\n"
        "- business logic belongs in `core/`\n"
        "- optimization logic belongs in `model/`\n"
        "- repeated-run logic belongs in `experiments/`\n"
        "- plotting/export logic belongs in `reporting/`\n"
        "- scripts mainly wire those layers together\n\n"
        "This is good practice because it makes the scripts:\n"
        "- easy to read\n"
        "- easy to debug\n"
        "- easy to replace or extend\n\n"
        "---\n\n"
        "## Strengths of the `scripts/` layer\n\n"
        "- clear runnable entry points\n"
        "- reproducible smoke tests\n"
        "- good examples of intended code usage\n"
        "- direct generation of report-ready outputs in `results/`\n\n"
        "---\n\n"
        "## Current limitations of the `scripts/` layer\n\n"
        "- some scripts are purpose-specific and not yet generalized into a command-line interface\n"
        "- several scripts rely on the full Xpress backend for rich route/KPI extraction\n"
        "- script naming is mostly consistent but could be standardized further in future cleanup\n\n"
        "---\n\n"
        "## Summary of `scripts/`\n\n"
        "The `scripts/` package is the executable control layer of the repository.\n\n"
        "It provides:\n"
        "- smoke tests\n"
        "- benchmark runners\n"
        "- sensitivity runners\n"
        "- CFA runners\n"
        "- penalty experiment runners\n"
        "- stochastic ETS runners\n"
        "- debugging tools\n\n"
        "This layer is what makes the rest of the architecture accessible in practice.\n\n"
    
    )
]

content = "".join(SECTIONS)

output_dir = Path("docs")
output_dir.mkdir(parents=True, exist_ok=True)

output_path = output_dir / "07_scripts.md"
output_path.write_text(content, encoding="utf-8")

print(f"Written: {output_path.resolve()}")
print("Preview in VS Code Markdown Preview or any Markdown viewer.")