from pathlib import Path

SECTIONS = [
    (
        "# Model Module Documentation\n\n"
        "## Purpose of `model/`\n\n"
        "The `model/` package contains the optimization layer of the repository.\n\n"
        "Its role is to transform a canonical `VSRPInstance` into a canonical\n"
        "`VSRPSolution` using one of several solver backends.\n\n"
        "This package is where the mathematical optimization model is actually built\n"
        "and solved.\n\n"
        "---\n\n"
        "## Files in `model/`\n\n"
        "| File | Main role |\n"
        "|---|---|\n"
        "| `base.py` | Abstract solver interface and shared solver helpers |\n"
        "| `xpress_solver.py` | Native full-feature Xpress backend |\n"
        "| `highs_solver.py` | HiGHS export-based backend |\n"
        "| `cbc_solver.py` | CBC export-based backend |\n"
        "| `mip_builder.py` | Solver-agnostic PuLP model builder used by open-source backends |\n\n"
        "---\n\n"
        "## Architectural role of `model/`\n\n"
        "The codebase is designed so that experiments do not depend directly on solver APIs.\n"
        "Instead, they depend on the abstract solver interface defined in `model/base.py`.\n\n"
        "This allows the same experiment code to run with:\n"
        "- Xpress\n"
        "- HiGHS\n"
        "- CBC\n\n"
        "without changing the experiment logic itself.\n\n"
        "The `model/` package is therefore the bridge between:\n"
        "- canonical problem objects from `core/` and `data/`\n"
        "- concrete optimization engines\n\n"
        "---\n\n"
        "## 1. `model/base.py`\n\n"
        "### Purpose\n\n"
        "`base.py` defines the common solver interface shared by all backends.\n\n"
        "This is the file that makes the architecture solver-agnostic.\n\n"
        "### Main components\n\n"
        "#### `SolveOptions`\n"
        "Stores generic solve controls such as:\n"
        "- time limit\n"
        "- relative MIP gap target\n"
        "- logging flag\n"
        "- optional random seed\n\n"
        "This gives experiments a unified way to configure different solvers.\n\n"
        "#### `BaseSolver`\n"
        "Abstract base class defining the common API:\n\n"
        "- `solve(instance, options)`\n"
        "- `is_available`\n\n"
        "Every concrete backend must implement this interface.\n\n"
        "#### `build_empty_solution()`\n"
        "Shared helper to build a canonical empty/error solution.\n\n"
        "This is useful when a solver:\n"
        "- is unavailable\n"
        "- errors during solve\n"
        "- returns no feasible solution\n\n"
        "### Why this file matters\n\n"
        "Without `base.py`, the rest of the repository would need solver-specific branches everywhere.\n"
        "With `base.py`, experiments can treat all solvers uniformly.\n\n"
        "---\n\n"
        "## 2. `model/xpress_solver.py`\n\n"
        "### Purpose\n\n"
        "`xpress_solver.py` is the **reference native backend** of the repository.\n\n"
        "It is the most complete solver implementation and the one used for:\n"
        "- full route reconstruction\n"
        "- strategy extraction\n"
        "- timeline reconstruction\n"
        "- container-outcome extraction\n"
        "- validation attachment\n"
        "- emissions attachment\n\n"
        "### Why Xpress is special in this project\n\n"
        "The Xpress backend is not just a solver wrapper. It is the only backend that\n"
        "currently reconstructs a **full canonical solution** object.\n\n"
        "That means it returns:\n"
        "- route legs\n"
        "- skipped and swapped ports\n"
        "- strategy tags\n"
        "- timeline entries\n"
        "- container delayed/misconnected outcomes\n"
        "- validation summary\n"
        "- emissions summary\n\n"
        "### Main internal stages\n\n"
        "#### Model build\n"
        "The Xpress backend:\n"
        "- builds the network from `core/network.py`\n"
        "- creates decision variables\n"
        "- adds flow, port-call, swap, strategy, delay, misconnection, and objective constraints\n\n"
        "#### Solve\n"
        "The model is solved through the native Xpress Python API.\n\n"
        "#### Extraction\n"
        "After solve, the backend reconstructs a canonical `VSRPSolution` from\n"
        "the selected variable values.\n\n"
        "### Why this file matters\n\n"
        "This is the repository’s most important optimization implementation.\n"
        "It is the benchmark reference against which the open-source backends are compared.\n\n"
        "---\n\n"
        "## 3. `model/mip_builder.py`\n\n"
        "### Purpose\n\n"
        "`mip_builder.py` contains the solver-agnostic **PuLP-based formulation builder**.\n\n"
        "It exists so that open-source solvers can solve the same model without depending\n"
        "on the native Xpress API.\n\n"
        "### Main role\n\n"
        "The builder creates the full VSRP mixed-integer model using PuLP and can export\n"
        "it to MPS format.\n\n"
        "This exported MPS is then read by:\n"
        "- HiGHS\n"
        "- CBC\n\n"
        "### Why this file matters\n\n"
        "This file is what makes the repository genuinely multi-solver.\n\n"
        "Without it, HiGHS and CBC would not have an independent model-construction path.\n\n"
        "### Formulation content\n\n"
        "The builder includes:\n"
        "- flow conservation\n"
        "- port-call constraints\n"
        "- swap-group constraints\n"
        "- strategy classification\n"
        "- delay indicators\n"
        "- misconnection logic\n"
        "- FuelEU penalty term when enabled\n"
        "- weighted operational/service objective\n\n"
        "### Important note\n\n"
        "The goal is formulation-level parity with the Xpress backend, not a separate model.\n"
        "That is why objective values can be meaningfully compared across solvers.\n\n"
        "---\n\n"
        "## 4. `model/highs_solver.py`\n\n"
        "### Purpose\n\n"
        "`highs_solver.py` is the HiGHS backend.\n\n"
        "It uses:\n"
        "- `mip_builder.py` to create the PuLP model\n"
        "- MPS export\n"
        "- the `highspy` API to solve the exported formulation\n\n"
        "### Current output level\n\n"
        "HiGHS currently returns a **partial canonical solution**.\n\n"
        "That means it reports:\n"
        "- objective value\n"
        "- runtime\n"
        "- MIP gap\n"
        "- best bound\n"
        "- node / iteration information where available\n\n"
        "but does **not** yet reconstruct:\n"
        "- route legs\n"
        "- timeline\n"
        "- container outcomes\n"
        "- validation or emissions summary\n\n"
        "### Why this file matters\n\n"
        "It provides an open-source benchmark point against the Xpress implementation.\n"
        "Even without full route extraction, it is very valuable for:\n"
        "- objective consistency testing\n"
        "- runtime benchmarking\n"
        "- gap / bound comparisons\n\n"
        "---\n\n"
        "## 5. `model/cbc_solver.py`\n\n"
        "### Purpose\n\n"
        "`cbc_solver.py` is the CBC backend.\n\n"
        "Like HiGHS, it uses:\n"
        "- the PuLP-based formulation builder\n"
        "- MPS export\n"
        "- a backend-specific API (`python-mip`) to solve the exported model\n\n"
        "### Current output level\n\n"
        "CBC also returns a **partial canonical solution**.\n\n"
        "It reports:\n"
        "- objective value\n"
        "- runtime\n"
        "- MIP gap where available\n"
        "- best bound where available\n"
        "- node count where available\n\n"
        "but not full route/timeline/container extraction.\n\n"
        "### Why this file matters\n\n"
        "It gives the repository a second open-source benchmark solver and helps confirm\n"
        "that the model is not dependent on a single commercial backend.\n\n"
        "---\n\n"
        "## Common optimization workflow\n\n"
        "All model backends follow the same high-level lifecycle:\n\n"
        "1. Receive a canonical `VSRPInstance`\n"
        "2. Build or export the optimization model\n"
        "3. Apply solve options\n"
        "4. Solve the model\n"
        "5. Extract available results into a canonical `VSRPSolution`\n"
        "6. Return the canonical result to the experiment or script layer\n\n"
        "This common lifecycle is one of the main reasons the repository is easy to benchmark.\n\n"
        "---\n\n"
        "## Relationship to the rest of the codebase\n\n"
        "### `model/` depends on `core/`\n"
        "The model layer uses:\n"
        "- canonical entities\n"
        "- network generation\n"
        "- validation\n"
        "- emissions\n"
        "- cost recomputation\n\n"
        "### `model/` depends on `data/`\n"
        "Indirectly, because instances are built in the data layer before being solved.\n\n"
        "### `experiments/` depends on `model/`\n"
        "Experiments choose which solver backend to use and pass instances into it.\n\n"
        "---\n\n"
        "## Why the separation between Xpress and PuLP builder matters\n\n"
        "There are effectively two modeling paths in the repository:\n\n"
        "### Path 1: native Xpress\n"
        "- direct variable creation in Xpress\n"
        "- direct solve\n"
        "- full extraction\n\n"
        "### Path 2: open-source replication\n"
        "- build equivalent formulation in PuLP\n"
        "- export to MPS\n"
        "- solve in HiGHS or CBC\n"
        "- partial extraction\n\n"
        "This separation matters because it allows the repository to demonstrate:\n"
        "- solver independence at the formulation level\n"
        "- benchmark comparability\n"
        "- native-backend richness vs open-source portability trade-offs\n\n"
        "---\n\n"
        "## Strengths of the `model/` layer\n\n"
        "- common solver interface\n"
        "- native full-feature reference backend\n"
        "- open-source benchmark backends\n"
        "- shared formulation logic across solvers\n"
        "- clear separation between solving and reporting\n\n"
        "---\n\n"
        "## Current limitations of the `model/` layer\n\n"
        "- only Xpress currently supports full canonical solution extraction\n"
        "- HiGHS and CBC are benchmark-capable but not yet route-extraction-capable\n"
        "- the delayed and misconnection logic uses conservative timing approximations\n"
        "- FuelEU remains a single-fuel linear penalty proxy, not a full multi-fuel model\n\n"
        "---\n\n"
        "## Summary of `model/`\n\n"
        "The `model/` package is the optimization engine of the repository.\n\n"
        "It provides:\n"
        "- a shared solver API\n"
        "- a full native Xpress implementation\n"
        "- open-source HiGHS and CBC benchmark backends\n"
        "- a solver-agnostic PuLP formulation builder\n\n"
        "This package is what turns the canonical problem objects from `core/` and `data/`\n"
        "into solved optimization outputs.\n\n"
        "---\n\n"
        "## Suggested next documentation layer\n\n"
        "After `model/`, the next most useful document is:\n"
        "- `05_experiments.md` — how benchmarking, sensitivity, CFA, penalty,\n"
        "  and stochastic ETS experiments are orchestrated\n"
    )
]

content = "".join(SECTIONS)

output_dir = Path("docs")
output_dir.mkdir(parents=True, exist_ok=True)

output_path = output_dir / "04_model.md"
output_path.write_text(content, encoding="utf-8")

print(f"Written: {output_path.resolve()}")
print("Preview in VS Code Markdown Preview or any Markdown viewer.")