import textwrap
from pathlib import Path

TREE = (
    ".\n"
    "├── core/\n"
    "│   ├── entities.py\n"
    "│   ├── network.py\n"
    "│   ├── costs.py\n"
    "│   ├── emissions.py\n"
    "│   ├── simulation.py\n"
    "│   └── validation.py\n"
    "│\n"
    "├── data/\n"
    "│   ├── base_instance.py\n"
    "│   └── instance_generator.py\n"
    "│\n"
    "├── model/\n"
    "│   ├── base.py\n"
    "│   ├── xpress_solver.py\n"
    "│   ├── highs_solver.py\n"
    "│   ├── cbc_solver.py\n"
    "│   └── mip_builder.py\n"
    "│\n"
    "├── experiments/\n"
    "│   ├── benchmark.py\n"
    "│   ├── sensitivity.py\n"
    "│   ├── cfa.py\n"
    "│   ├── penalty_sensitivity.py\n"
    "│   └── stochastic_ets.py\n"
    "│\n"
    "├── reporting/\n"
    "│   ├── export.py\n"
    "│   ├── benchmark_plots.py\n"
    "│   ├── benchmark_reporting.py\n"
    "│   ├── sensitivity_plots.py\n"
    "│   ├── emissions_plots.py\n"
    "│   ├── cfa_plots.py\n"
    "│   ├── penalty_sensitivity_plots.py\n"
    "│   └── stochastic_ets_plots.py\n"
    "│\n"
    "├── scripts/\n"
    "│   ├── smoke_test.py\n"
    "│   ├── benchmark_smoke.py\n"
    "│   ├── sensitivity_smoke.py\n"
    "│   ├── cfa_smoke.py\n"
    "│   ├── transshipment_smoke.py\n"
    "│   ├── stochastic_ets_smoke.py\n"
    "│   ├── penalty_sensitivity_smoke.py\n"
    "│   ├── penalty_speedup_multiseed_smoke.py\n"
    "│   ├── penalty_plot_smoke.py\n"
    "│   └── debug_alpha_case.py\n"
    "│\n"
    "└── results/\n"
    "    ├── figures/\n"
    "    └── tables/\n"
)

SECTIONS = [

("# VSRP Extensions & Benchmarking\n\n"
"**Vessel Schedule Recovery Problem — Engineering-Grade Extension**\n\n"
"TJL Optimization Case Study | March 2026\n\n"
"---\n\n"
"## Overview\n\n"
"This repository extends the FICO Xpress community notebook implementation of the\n"
"Vessel Schedule Recovery Problem (VSRP) into a fully reproducible, solver-agnostic\n"
"codebase that:\n\n"
"1. **Completes the baseline model** — implements Port Swapping (Level B) and full\n"
"   Transshipment Misconnection Logic omitted from the original notebook\n"
"2. **Incorporates CO2 regulatory compliance** — EU ETS phase-in, IMO CII/EEXI,\n"
"   FuelEU Maritime penalty, and green recovery trade-off analysis\n"
"3. **Benchmarks open-source solvers** — HiGHS and CBC via a PuLP-based\n"
"   solver-agnostic MIP layer, benchmarked against FICO Xpress\n"
"4. **Implements a CFA policy** — Cost Function Approximation with additive, decay,\n"
"   and SPSA update rules under full stochastic uncertainty\n\n"
"---\n\n"
"## How to Run Scripts\n\n"
"All scripts must be run as **modules from the project root** so that Python\n"
"resolves internal imports correctly.\n\n"
"**Windows (PowerShell):**\n\n"
"```powershell\n"
"python -m scripts.smoke_test\n"
"python -m scripts.benchmark_smoke\n"
"python -m scripts.sensitivity_smoke\n"
"# etc.\n"
"```\n\n"
"**Linux / macOS:**\n\n"
"```bash\n"
"python -m scripts.smoke_test\n"
"python -m scripts.benchmark_smoke\n"
"python -m scripts.sensitivity_smoke\n"
"# etc.\n"
"```\n\n"
"> **Why `-m`?** Running `python scripts/smoke_test.py` directly does not add\n"
"> the project root to `sys.path`, causing `ModuleNotFoundError` for imports\n"
"> like `from core.entities import...`. The `-m` flag runs the file as a\n"
"> module and automatically includes the project root in the path.\n\n"
"---\n\n"
"## Repository Structure\n\n"),

("```\n" + TREE + "```\n\n"
"---\n\n"
"## Installation\n\n"
"### Requirements\n\n"
"- Python 3.11+\n"
"- FICO Xpress (community license sufficient for smoke tests)\n"
"- Open-source solver dependencies (optional, for benchmarking)\n\n"
"### Setup\n\n"
"```powershell\n"
"git clone <repo-url>\n"
"cd VesselSchedulingProblem\n\n"
"python -m venv.venv\n"
".venv\\Scripts\\activate          # Windows PowerShell\n"
"source.venv/bin/activate       # Linux/macOS\n\n"
"pip install -r requirements.txt\n"
"```\n\n"
"### `requirements.txt`\n\n"
"```\n"
"xpress\n"
"pulp\n"
"highspy\n"
"mip\n"
"numpy\n"
"pandas\n"
"matplotlib\n"
"openpyxl\n"
"scipy\n"
"```\n\n"
"> **Note:** FICO Xpress must be installed separately. The community license is\n"
"> bundled with the `xpress` Python package. HiGHS (`highspy`) and CBC (`mip`)\n"
"> are optional — the codebase degrades gracefully if they are unavailable.\n\n"
"---\n\n"
"## Quick Start\n\n"
"```powershell\n"
"python -m scripts.smoke_test\n"
"```\n\n"
"Expected output includes:\n\n"
"```\n"
"overall_valid            : True\n"
"strategy_consistent      : True\n"
"max_constraint_violation : 0.0\n"
"objective_recompute_abs_gap : 0.000000\n"
"```\n\n"
"---\n\n"
"## Running Experiments\n\n"
"All scripts write outputs to `results/figures/` and `results/tables/`.\n\n"
"### 1. Baseline correctness\n\n"
"```powershell\n"
"python -m scripts.smoke_test\n"
"```\n\n"
"Validates route, strategy, timeline, container outcomes, and cost consistency\n"
"for a single Xpress solve.\n\n"
"### 2. Transshipment logic\n\n"
"```powershell\n"
"python -m scripts.transshipment_smoke\n"
"```\n\n"
"Tests the full Li et al. (2023) transshipment misconnection logic across\n"
"Xpress, HiGHS, and CBC on a mixed direct/transshipment container set.\n\n"
"### 3. Solver benchmarking\n\n"
"```powershell\n"
"python -m scripts.benchmark_smoke\n"
"```\n\n"
"Runs Xpress, HiGHS, and CBC on two random instances. Reports:\n\n"
"- Objective value, runtime, MIP gap, best bound\n"
"- Route validity, strategy consistency, constraint violations\n"
"- Stability metrics (obj_std, gap_std, pct_feasible, pct_optimal)\n\n"
"### 4. Sensitivity analysis\n\n"
"```powershell\n"
"python -m scripts.sensitivity_smoke\n"
"```\n\n"
"Produces:\n\n"
"- Alpha sweep (0.0 to 1.0): objective, cost decomposition, CO2, strategy mix\n"
"- Delay sweep (0h to 108h): objective, emissions, service outcomes\n"
"- ETS price sweep (25 to 130 EUR/tCO2): post-solve ETS exposure\n"
"- Green recovery trade-off plots\n"
"- CII profile across delay scenarios\n\n"
"### 5. CFA policy\n\n"
"```powershell\n"
"python -m scripts.cfa_smoke\n"
"```\n\n"
"Trains and tests four policies (Baseline, Additive, Decay, SPSA) over\n"
"10 training and 20 test episodes under full stochastic uncertainty.\n"
"Produces policy comparison, tail risk, and ETS compliance figures.\n\n"
"### 6. Penalty sensitivity\n\n"
"```powershell\n"
"python -m scripts.penalty_sensitivity_smoke\n"
"python -m scripts.penalty_speedup_multiseed_smoke\n"
"python -m scripts.penalty_plot_smoke\n"
"```\n\n"
"Sweeps swap and speed-up penalties across four random seeds.\n"
"Identifies strategy activation thresholds and route stability.\n\n"
"### 7. Stochastic ETS exposure\n\n"
"```powershell\n"
"python -m scripts.stochastic_ets_smoke\n"
"```\n\n"
"Solves one deterministic instance, then evaluates ETS cost exposure\n"
"across 50 stochastic carbon price scenarios. Reports VaR-like tail metrics.\n\n"
"### 8. Diagnostic tool\n\n"
"```powershell\n"
"python -m scripts.debug_alpha_case\n"
"```\n\n"
"Prints detailed route, timeline, validation, cost, and emissions output\n"
"for a single alpha scenario. Useful for investigating specific cases.\n\n"
"---\n\n"
"## Model Description\n\n"
"### Problem\n\n"
"The VSRP determines optimal recovery actions when a liner vessel faces\n"
"disruptions. Given an initial delay, the model selects:\n\n"
"- Which ports to visit or skip\n"
"- Sailing speed on each leg\n"
"- Port handling duration (standard or expedited)\n"
"- Whether to reorder port visits (swap)\n\n"
"to minimise a weighted combination of operational and service disruption costs.\n\n"
"### Objective\n\n"
"```\n"
"min  (1 - alpha) * C_op  +  alpha * C_svc\n"
"```\n\n"
"where `alpha` in [0,1] controls the service/cost trade-off.\n\n"
"**Operational cost** includes fuel, port handling, strategy penalties\n"
"(speed-up, expedited, omission, swap), port-specific penalties, and\n"
"optionally the FuelEU non-compliance penalty.\n\n"
"**Service cost** includes delay penalties and misconnection penalties.\n\n"
"### Recovery Strategies\n\n"
"| Strategy | Description |\n"
"|---|---|\n"
"| Speed adjustment | Sail faster (FAST 25kn) or slower (SLOW 15kn) than nominal (20kn) |\n"
"| Expedited handling | Reduce port-call duration from 12h to 8h |\n"
"| Port omission | Skip one or more planned port calls |\n"
"| Port swapping | Reorder two port visits (non-adjacent, Brouer et al. 2013) |\n\n"
"### Swap Implementation\n\n"
"Non-adjacent port swapping is implemented using:\n\n"
"- Three-leg swap groups (leg A: approach, leg B: reverse, leg C: continue)\n"
"- Binary ordering variables z_ij with antisymmetry and transitivity constraints\n"
"- `max_swap_distance=2` bound to prevent degenerate routes\n"
"- Swap penalty charged once per active swap group\n\n"
"### Transshipment Misconnection\n\n"
"Full Li et al. (2023) logic: a container is misconnected if the vessel\n"
"arrives at its transshipment port after `connecting_service_deadline_h`.\n"
"Non-connecting edges are identified at model-build time and constrained\n"
"to force `o[c] = 1`.\n\n"
"### Emissions and Regulatory Compliance\n\n"
"| Module | Coverage |\n"
"|---|---|\n"
"| CO2 accounting | Cubic fuel model per leg, VLSFO emission factor 3.114 tCO2/t |\n"
"| EU ETS | Phase-in schedule (40/70/100% for 2024/2025/2026+), stochastic carbon price |\n"
"| IMO CII | Attained vs required CII, A-E rating (IMO MEPC 2024 reference lines) |\n"
"| IMO EEXI | Vessel-level compliance check (speed-limit precondition) |\n"
"| FuelEU Maritime | GHG intensity limit interpolation, energy-based penalty formula |\n\n"
"**Single-fuel assumption (VLSFO):** All legs burn VLSFO at constant GHG intensity\n"
"91.16 gCO2eq/MJ. The FuelEU penalty is therefore linear in total fuel burn.\n"
"The 2026 FuelEU limit is approximately 88.61 gCO2eq/MJ (interpolated between\n"
"2025=89.34 and 2030=85.69), making VLSFO always non-compliant from 2025 onward.\n\n"
"---\n\n"
"## CFA Policy\n\n"
"Following the Powell (2022) Cost Function Approximation framework:\n\n"
"```\n"
"parametric optimization  ->  simulator  ->  parameter update  ->  repeat\n"
"```\n\n"
"**Theta:** Per-destination promise tightening vector. Higher theta at port p\n"
"forces the MIP to treat container deadlines at p as tighter, encouraging\n"
"more aggressive recovery.\n\n"
"**Uncertainty sources:**\n\n"
"| Source | Distribution |\n"
"|---|---|\n"
"| Initial delay | Truncated normal, mean=55h, std=10h |\n"
"| Port handling multipliers | Truncated normal, mean=1.0, std=0.1, per port |\n"
"| Weather speed factors | Truncated normal, mean=1.0, std=0.05, per leg |\n"
"| Carbon price | Truncated normal, mean=65, std=15 EUR/tCO2 |\n"
"| Fuel price | Truncated normal, mean=600, std=80 USD/tonne |\n\n"
"**Update policies:**\n\n"
"| Policy | Rule |\n"
"|---|---|\n"
"| Additive | theta_p += step * misses_p |\n"
"| Decay | Increase where misses occur, decrease where none |\n"
"| SPSA | Simultaneous perturbation gradient estimate with Rademacher delta |\n\n"
"**Results (20 test episodes):**\n\n"
"| Policy | Avg missed | Avg service cost | vs Baseline |\n"
"|---|---|---|---|\n"
"| Baseline | 4.00 | $298,912 | — |\n"
"| Additive | 3.60 | $272,439 | -8.9% |\n"
"| Decay | 3.70 | $277,196 | -7.3% |\n"
"| **SPSA** | **3.00** | **$243,900** | **-18.4%** |\n\n"
"SPSA achieves zero variance (p90 = p95 = mean = $243,900), demonstrating\n"
"robust convergence to a consistently better policy.\n\n"
"---\n\n"
"## Benchmark Results\n\n"
"Two random instances, three solvers, `time_limit=60s`, `mip_gap=0.01`.\n\n"
"| Solver | Avg objective | Avg runtime | MIP gap | Feasible | Optimal |\n"
"|---|---|---|---|---|---|\n"
"| Xpress | $501,429 | 0.015s | 0.0% | 100% | 100% |\n"
"| HiGHS | $501,429 | 0.050s | 0.0% | 100% | 100% |\n"
"| CBC | $501,429 | 0.258s | 0.0% | 100% | 100% |\n\n"
"All three solvers find identical optimal solutions. Xpress is 3.3x faster\n"
"than HiGHS and 17x faster than CBC on these instances.\n\n"
"**Solver independence:** HiGHS and CBC use a PuLP-based MIP builder\n"
"(`model/mip_builder.py`) that is fully independent of Xpress. The formulation\n"
"is identical across all three solvers.\n\n"
"---\n\n"
"## Key Design Decisions\n\n"
"### Solver-agnostic architecture\n\n"
"All experiments use `BaseSolver` as the interface. Swapping solvers requires\n"
"only changing the solver object passed to experiment functions — no model\n"
"changes needed.\n\n"
"### Promised arrival calibration\n\n"
"Container promised arrivals are calibrated to the expected initial delay\n"
"(48h) at nominal speed (20 knots). This ensures the delay constraint\n"
"correctly classifies containers as on-time or late across the delay sweep\n"
"range (0h to 108h).\n\n"
"### Swap penalty charging\n\n"
"The swap penalty is charged once per active swap group (not once per swapped\n"
"port) in both the MIP objective and the post-solve cost recomputation.\n"
"This ensures `objective_recompute_abs_gap = 0` for all instances.\n\n"
"### FuelEU penalty formula\n\n"
"The corrected energy-based formula (Article 23, FuelEU Maritime Regulation):\n\n"
"```\n"
"Penalty = max(0, g - g*) / g  *  F_total  *  penalty_rate  *  FX\n"
"```\n\n"
"where `g` = VLSFO GHG intensity (91.16 gCO2eq/MJ), `g*` = FuelEU limit,\n"
"`F_total` = total fuel burned (tonnes), `penalty_rate` = EUR 2,400 per tonne\n"
"VLSFO equivalent, `FX` = EUR/USD conversion rate.\n\n"
"---\n\n"
"## Limitations and Future Work\n\n"
"| Limitation | Notes |\n"
"|---|---|\n"
"| Single-fuel (VLSFO) | Multi-fuel would require per-leg fuel-choice variables |\n"
"| Per-voyage FuelEU | Regulation applies annually; per-voyage is a standard approximation |\n"
"| Delay constraint approximation | Uses nominal speed on prior legs; big-M formulation would be exact |\n"
"| time_to_first_feasible | Unavailable on Xpress community license |\n"
"| Delay sweep flat above 48h | Structural property of this container set; more containers would show more variation |\n"
"| Port swapping rarely activates | Consistent with Brouer et al. (2013) finding that swap is rarely optimal |\n\n"
"---\n\n"
"## References\n\n"
"1. Brouer, B.D. et al. (2013). The Vessel Schedule Recovery Problem (VSRP).\n"
"   *European Journal of Operational Research*, 224(2), 362-374.\n\n"
"2. Li, S. et al. (2023). Vessel schedule recovery strategy in liner shipping\n"
"   considering expected disruption. *Ocean and Coastal Management*, 237, 106514.\n\n"
"3. Hu, Liu, Jin, Wang (2024). Liner disruption recovery problem with emission\n"
"   control area policies. *Transportation Research Part D*, 132, 104227.\n\n"
"4. Zhou et al. (2024). Strategy and Impact of Liner Shipping Schedule Recovery\n"
"   under ECA Regulation. *Journal of Marine Science and Engineering*.\n\n"
"5. Li, S. and Wang, T. (2025). How emissions trading system affects liner ship\n"
"   disruption recovery. *Transport Policy*, 169, 191-208.\n\n"
"6. Powell, W.B. (2022). *Reinforcement Learning and Stochastic Optimization*.\n"
"   Wiley. [CFA framework]\n\n"
"7. IMO MEPC.338(76) — CII reference lines for container ships.\n\n"
"8. Regulation (EU) 2023/957 — EU ETS maritime phase-in schedule.\n\n"
"9. FuelEU Maritime Regulation — GHG intensity limits and Article 23 penalty.\n\n"),

]

readme = "".join(SECTIONS)

output_path = Path("README.md")
output_path.write_text(readme, encoding="utf-8")

print(f"Written: {output_path.resolve()}")
print("Preview: grip README.md   or   Ctrl+Shift+V in VS Code")