import textwrap
from pathlib import Path

SECTIONS = [
    (
        "# Project Architecture\n\n"
        "## Purpose\n\n"
        "This document explains the high-level architecture of the VSRP codebase:\n"
        "- what each folder is responsible for\n"
        "- how data flows through the system\n"
        "- how scripts, experiments, solvers, and reporting interact\n\n"
        "The design goal of the repository is to provide a **solver-agnostic, reproducible, engineering-grade extension** of the Vessel Schedule Recovery Problem (VSRP).\n\n"
        "---\n\n"
        "## Core design principle\n\n"
        "The central architectural idea is:\n\n"
        "> **all solver backends and experiments should communicate through canonical problem and solution objects**\n\n"
        "The two most important shared objects are:\n"
        "- `VSRPInstance`\n"
        "- `VSRPSolution`\n\n"
        "These are defined in `core/entities.py` and are used across:\n"
        "- instance generation\n"
        "- model solving\n"
        "- validation\n"
        "- emissions\n"
        "- benchmarking\n"
        "- plotting\n\n"
        "This allows the repository to remain modular and mostly solver-independent.\n\n"
        "---\n\n"
        "## Folder responsibilities\n\n"
        "### `core/`\n"
        "Shared solver-agnostic logic:\n"
        "- canonical dataclasses\n"
        "- network construction\n"
        "- cost recomputation\n"
        "- emissions and regulatory metrics\n"
        "- simulation under uncertainty\n"
        "- validation\n\n"
        "This is the **common logic layer** of the codebase.\n\n"
        "### `data/`\n"
        "Problem-input generation:\n"
        "- fixed case-study route and distances\n"
        "- random container generation\n"
        "- base instance factory\n\n"
        "This layer constructs the inputs passed to the solvers.\n\n"
        "### `model/`\n"
        "Optimization layer:\n"
        "- abstract solver interface\n"
        "- native Xpress backend\n"
        "- open-source HiGHS and CBC backends\n"
        "- solver-agnostic PuLP MIP builder\n\n"
        "This layer transforms `VSRPInstance` objects into `VSRPSolution` objects.\n\n"
        "### `experiments/`\n"
        "Experiment orchestration:\n"
        "- benchmarking\n"
        "- sensitivity analysis\n"
        "- CFA training/testing\n"
        "- penalty sensitivity\n"
        "- stochastic ETS exposure\n\n"
        "This layer repeatedly builds instances, solves them, and converts results into tidy tabular outputs.\n\n"
        "### `reporting/`\n"
        "Output generation:\n"
        "- table saving\n"
        "- figure saving\n"
        "- benchmark plots\n"
        "- sensitivity plots\n"
        "- emissions plots\n"
        "- CFA plots\n"
        "- penalty sensitivity plots\n"
        "- stochastic ETS plots\n\n"
        "This layer consumes experiment outputs and writes files into `results/`.\n\n"
        "### `scripts/`\n"
        "Executable entry points:\n"
        "- smoke tests\n"
        "- diagnostics\n"
        "- experiment runners\n\n"
        "These are the top-level user-facing commands.\n\n"
        "### `results/`\n"
        "Generated artifacts:\n"
        "- figures\n"
        "- tables\n\n"
        "This directory is the sink for experiment outputs.\n\n"
        "---\n\n"
        "## High-level dependency structure\n\n"
        "```text\n"
        "scripts\n"
        "   ↓\n"
        "experiments\n"
        "   ↓\n"
        "model\n"
        "   ↓\n"
        "core + data\n"
        "   ↓\n"
        "reporting\n"
        "   ↓\n"
        "results\n"
        "```\n\n"
        "A more detailed view is:\n\n"
        "```text\n"
        "+------------------+\n"
        "|     scripts/     |\n"
        "| smoke tests,     |\n"
        "| debug runners,   |\n"
        "| experiment entry |\n"
        "| points           |\n"
        "+--------+---------+\n"
        "         |\n"
        "         v\n"
        "+------------------+\n"
        "|  experiments/    |\n"
        "| benchmark,       |\n"
        "| sensitivity,     |\n"
        "| CFA, penalty,    |\n"
        "| stochastic ETS   |\n"
        "+--------+---------+\n"
        "         |\n"
        "         v\n"
        "+------------------+         +------------------+\n"
        "|     model/       | <-----> |      data/       |\n"
        "| solvers + MIP    |         | base instance,   |\n"
        "| builder          |         | container gen    |\n"
        "+--------+---------+         +------------------+\n"
        "         |\n"
        "         v\n"
        "+------------------+\n"
        "|      core/       |\n"
        "| entities,        |\n"
        "| network, costs,  |\n"
        "| emissions,       |\n"
        "| simulation,      |\n"
        "| validation       |\n"
        "+--------+---------+\n"
        "         |\n"
        "         v\n"
        "+------------------+\n"
        "|   reporting/     |\n"
        "| tables, plots,   |\n"
        "| exports          |\n"
        "+--------+---------+\n"
        "         |\n"
        "         v\n"
        "+------------------+\n"
        "|    results/      |\n"
        "| saved figures    |\n"
        "| and tables       |\n"
        "+------------------+\n"
        "```\n\n"
        "---\n\n"
        "## Runtime execution flow\n\n"
        "### Example: running a smoke script\n\n"
        "Command:\n\n"
        "```bash\n"
        "python -m scripts.smoke_test\n"
        "```\n\n"
        "Execution flow:\n\n"
        "1. `scripts/smoke_test.py`\n"
        "   - generates containers\n"
        "   - builds a base instance\n"
        "   - selects the Xpress solver\n"
        "   - calls the solver\n\n"
        "2. `model/xpress_solver.py`\n"
        "   - builds the network\n"
        "   - creates the MIP\n"
        "   - solves the instance\n"
        "   - reconstructs a canonical solution\n\n"
        "3. `core/validation.py`\n"
        "   - validates route, strategies, timeline, and structural consistency\n\n"
        "4. `core/emissions.py`\n"
        "   - computes fuel, CO2, ETS, FuelEU, and CII metrics\n\n"
        "5. `core/costs.py`\n"
        "   - recomputes cost breakdown and checks consistency with the reported objective\n\n"
        "6. `scripts/smoke_test.py`\n"
        "   - prints the final structured output\n\n"
        "---\n\n"
        "## Data flow\n\n"
        "### Inputs\n\n"
        "The main inputs are:\n"
        "- fixed port rotation and distance matrix from `data/base_instance.py`\n"
        "- randomly generated containers from `data/instance_generator.py`\n"
        "- solver settings from `model/base.py`\n"
        "- optional experiment parameters from `experiments/*`\n\n"
        "### Canonical problem object\n\n"
        "All optimization starts from:\n\n"
        "- `VSRPInstance`\n\n"
        "This object packages:\n"
        "- ports\n"
        "- distance matrix\n"
        "- containers\n"
        "- penalties\n"
        "- speed levels\n"
        "- port-call durations\n"
        "- disruption parameters\n"
        "- regulatory settings\n\n"
        "### Canonical solution object\n\n"
        "All solver outputs are normalized into:\n\n"
        "- `VSRPSolution`\n\n"
        "This object may contain:\n"
        "- route legs\n"
        "- skipped / swapped ports\n"
        "- strategy decisions\n"
        "- timeline\n"
        "- container outcomes\n"
        "- solver statistics\n"
        "- validation summary\n"
        "- emissions summary\n"
        "- metadata\n\n"
        "---\n\n"
        "## Solver architecture\n\n"
        "### Native backend\n\n"
        "`model/xpress_solver.py` is the reference implementation:\n"
        "- full model build\n"
        "- full solution extraction\n"
        "- validation\n"
        "- emissions attachment\n\n"
        "### Open-source backends\n\n"
        "`model/highs_solver.py` and `model/cbc_solver.py` use:\n"
        "- `model/mip_builder.py`\n"
        "- MPS export\n"
        "- backend-specific solve APIs\n\n"
        "They currently return **partial canonical solutions**:\n"
        "- objective\n"
        "- runtime\n"
        "- bounds\n"
        "- gap\n"
        "- availability metadata\n\n"
        "They do **not** yet reconstruct full route/timeline/container outputs.\n\n"
        "---\n\n"
        "## Why the architecture matters\n\n"
        "This structure makes the codebase:\n"
        "- easier to benchmark across solvers\n"
        "- easier to test\n"
        "- easier to document\n"
        "- easier to extend with new experiments\n"
        "- more robust than a single large notebook\n\n"
        "It also separates:\n"
        "- optimization logic\n"
        "- simulation logic\n"
        "- reporting logic\n"
        "- experiment orchestration\n\n"
        "which is essential for reproducibility.\n\n"
        "---\n\n"
        "## Key architectural strengths\n\n"
        "- canonical shared entities\n"
        "- solver-agnostic core logic\n"
        "- native + export-based solver support\n"
        "- experiment functions returning tidy DataFrames\n"
        "- reporting layer isolated from optimization layer\n"
        "- smoke scripts for end-to-end verification\n\n"
        "---\n\n"
        "## Known architectural limitations\n\n"
        "- HiGHS and CBC are currently partial-solution backends\n"
        "- Xpress is the only backend with full route/timeline/container extraction\n"
        "- some timing logic uses conservative approximation rather than full exact per-container timing variables\n"
        "- regulatory modules are implemented under a single-fuel VLSFO assumption\n\n"
        "---\n\n"
        "## Suggested next documentation layers\n\n"
        "After this architecture overview, the next useful documents are:\n"
        "- `02_core.md`\n"
        "- `03_data.md`\n"
        "- `04_model.md`\n"
        "- `05_experiments.md`\n"
        "- `06_reporting.md`\n"
        "- `07_scripts.md`\n"
    ),
]

readme = "".join(SECTIONS)

output_dir = Path("docs")
output_dir.mkdir(parents=True, exist_ok=True)

output_path = output_dir / "01_architecture.md"
output_path.write_text(readme, encoding="utf-8")

print(f"Written: {output_path.resolve()}")
print("Preview in VS Code Markdown Preview or any Markdown viewer.")